version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node-container
    ports:
      - '9999:9999'
